### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ghost** [nunofgs/rpi-crashplan#1]
Hello,

When trying to run this, I get the following error message on startup:

[06.08.16 11:33:20.698 WARN    main                 root                                    ] Failed to load config, using default. java.lang.Exception: DEFAULT CONFIG FILE MISSING! defaultConfigFile=/usr/local/crashplan/conf/default.service.xml
[06.08.16 11:33:20.700 INFO    main                 root                                    ] END Loading Configuration
[06.08.16 11:33:20.715 WARN    main                 com.code42.utils.PropertiesUtil         ] Exception loading Properties - file=conf/service.log.properties, java.io.FileNotFoundException, java.io.FileNotFoundException
java.io.FileNotFoundException
    at com.code42.utils.PropertiesUtil.load(PropertiesUtil.java:108)
    at com.code42.utils.PropertiesUtil.load(PropertiesUtil.java:88)
    at com.code42.utils.PropertiesUtil.load(PropertiesUtil.java:72)
    at com.backup42.service.CPService.readLoggingConfiguration(CPService.java:1646)
    at com.backup42.service.CPService.start(CPService.java:337)
    at com.backup42.service.CPService.main(CPService.java:1865)

Exiting!!! java.lang.NullPointerException
java.lang.NullPointerException
    at com.backup42.service.CPService.start(CPService.java:363)
    at com.backup42.service.CPService.main(CPService.java:1865)
[06.08.16 11:33:21.078 INFO    main                 root                                    ] ****\*  STOPPING  *****
[06.08.16 11:33:21.084 INFO    Thread-0             root                                    ] Stopping service...
[06.08.16 11:33:21.192 INFO    Thread-0             root                                    ] SystemWatcher stopped.
[06.08.16 11:33:21.197 INFO    Thread-0             root                                    ] Service stopped
pi@raspberrypi:~ $ 

Any ideas what might be wrong? I am fairly new to Docker so don't really know how to install the missing conf/service.log.properties file. It looks like this is packaged in this repository, but it seems that the file is not properly installed when I try to run the Docker container.

Docker version is:

pi@raspberrypi:~ $ docker --version
Docker version 1.8.1, build d12ea79-dirty

**Comment by nunofgs** [comment]
Hi @petka535,

Unfortunately I no longer have a raspberry pi to test this on. Maybe someone else can help out?

**Comment by ppachur** [comment]
Hi.

It is not capable of reading files in the config directory. Add this path to the Dockerfile and it will run (right before linking the conf-folders).

`ADD ./config /config` 

Patrick
